version: '3.7'

services:
  defi-dev-db:
    container_name: defi-dev-db
    image: defi-dev-db-image
    build: .
    networks:
      - defi-network
    ports:
      - '5431:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pg12
      - POSTGRES_DB=dev
      - POSTGRES_USER=rootuser
      - POSTGRES_PASSWORD=password
networks:
  defi-network:
